### ISSUE TITLE
No suitable driver found for jdbc:neo4j://localhost:7474

### ISSUE THREAD

**Issue by scheung38** [neo4j-examples/movies-java-spring-boot-jdbc#1]
$ neo4j start
Starting Neo4j Server...WARNING: not changing user
process [7418]... waiting for server to be ready......... OK.
http://localhost:7474/ is ready.

then in same directory

$ mvn spring-boot:run

returns:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: No suitable driver found for jdbc:neo4j://localhost:7474

Why is that, anyone?

**Comment by jexp** [comment]
fixed

**Comment by ftmzyldrm** [comment]
although following the instructions (setting url into application props, and be sure working the neo4j server ...) , i got the same problem. how did you fix it ? thanks

**Comment by gensior** [comment]
I've got the same problem as well. I cloned the repo, use `mvn spring-boot:run`, and it appears to start up. But when I access http://localhost:8080/graph I get an org.springframework
.jdbc.CannotGetJdbcConnectionException exception stating "No suitable driver found for jdbc:neo4j:http://localhost:7474".
